/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
}

description = "Vertigram Annotations"
