/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.vertx.vertx.core)
    api(libs.io.vertx.vertx.lang.kotlin)
    api(libs.io.vertx.vertx.lang.kotlin.coroutines)
    api(project(":vertigram"))
    api(project(":vertigram-telegram-client"))
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.slf4j)
    compileOnly(libs.ch.qos.logback.logback.classic)
}

description = "Vertigram Logback"
