/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.vertigram-module")
}

dependencies {
    api(libs.bundles.vertx.core)
    api(libs.bundles.kotlin.std)
    api(libs.bundles.logback)

    api(project(":vertigram"))
    api(project(":vertigram-telegram-client"))
}

description = "Vertigram Logback"
