/*
 * This file was generated by the Gradle 'init' task.
 */


rootProject.name = "vertigram-all"
//include(":vertigram-logback")
//include(":vertigram-annotations")
//include(":vertigram-parent-internal")
//include(":vertigram-core")
//include(":vertigram-parent")
//include(":vertigram")
//include(":vertigram-jooq")
//include(":vertigram-telegram-client")
//include(":vertigram-codegen")
//include(":vertigram-bom")
include(":vertigram-util")
