/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.com.zaxxer.hikaricp)
    api(libs.io.vertx.vertx.core)
    api(libs.io.vertx.vertx.jdbc.client)
    api(libs.io.vertx.vertx.lang.kotlin)
    api(libs.io.vertx.vertx.lang.kotlin.coroutines)
    api(libs.org.flywaydb.flyway.core)
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.core.jvm)
    api(libs.org.jetbrains.kotlinx.kotlinx.coroutines.jdk8)
    api(libs.org.jooq.jooq)
    api(libs.org.jooq.jooq.codegen)
    api(libs.org.jooq.jooq.meta)
    api(libs.org.postgresql.postgresql)
    api(libs.org.slf4j.slf4j.api)
    api(project(":vertigram-util"))
}

description = "Vertigram jOOQ"
