import org.jetbrains.dokka.gradle.DokkaTaskPartial

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.vertigram-module")
}

dependencies {
    implementation(libs.bundles.jackson)
    implementation(project(":vertigram-jooq-app-api"))
    implementation(libs.bundles.testcontainers)
    implementation(libs.bundles.jackson)
    implementation(libs.bundles.hikari)
    implementation(libs.bundles.flyway)
    implementation(libs.bundles.slf4j.api)
    implementation(libs.bundles.logback)
    implementation(libs.bundles.jooq.codegen)
    implementation(libs.jackson.dataformat.xml)

    testImplementation(libs.junit.api)
    testRuntimeOnly (libs.junit.engine)

    dokkaPlugin(libsInternal.dokka.versioning.plugin)
}

description = "Vertigram jOOQ app"

tasks.withType<DokkaTaskPartial>().configureEach {
    onlyIf { false }
}