package ski.gagar.vertigram.telegram.types.colors

import com.fasterxml.jackson.annotation.JsonValue

/**
 * An enum, representing a value for [ski.gagar.vertigram.telegram.types.Chat.FullInfo.profileAccentColor].
 *
 * See [Profile Accent Colors](https://core.telegram.org/bots/api#profile-accent-colors)
 * in Telegram docs for up-to-date reference.
 */
enum class ProfileAccentColor(
    /**
     * An id of the color, according to the docs
     */
    @JsonValue val id: Int,
    /**
     * List of colors, used in light Telegram theme
     */
    val light: List<RgbColor>,
    /**
     * List of colors, used in light Telegram theme
     */
    val dark: List<RgbColor> = light
) {
    RED(
        0,
        listOf(
            RgbColor.fromInt(0xBA5650)
        ),
        listOf(
            RgbColor.fromInt(0x9C4540)
        ),
    ),
    ORANGE(
        1,
        listOf(
            RgbColor.fromInt(0xC27C3E)
        ),
        listOf(
            RgbColor.fromInt(0x945E2C)
        ),
    ),
    PURPLE(
        2,
        listOf(
            RgbColor.fromInt(0x956AC8)
        ),
        listOf(
            RgbColor.fromInt(0x715099)
        ),
    ),
    GREEN(
        3,
        listOf(
            RgbColor.fromInt(0x49A355)
        ),
        listOf(
            RgbColor.fromInt(0x33713B)
        ),
    ),
    CYAN(
        4,
        listOf(
            RgbColor.fromInt(0x3E97AD)
        ),
        listOf(
            RgbColor.fromInt(0x387E87)
        ),
    ),
    BLUE(
        5,
        listOf(
            RgbColor.fromInt(0x5A8FBB)
        ),
        listOf(
            RgbColor.fromInt(0x477194)
        ),
    ),
    PINK(
        6,
        listOf(
            RgbColor.fromInt(0xB85378)
        ),
        listOf(
            RgbColor.fromInt(0x944763)
        ),
    ),
    GRAY(
        7,
        listOf(
            RgbColor.fromInt(0x7F8B95)
        ),
        listOf(
            RgbColor.fromInt(0x435261)
        ),
    ),
    RED_ORANGE(
        8,
        listOf(
            RgbColor.fromInt(0xC9565D),
            RgbColor.fromInt(0xD97C57)
        ),
        listOf(
            RgbColor.fromInt(0x994343),
            RgbColor.fromInt(0xAC583E)
        ),
    ),
    YELLOW_ORANGE(
        9,
        listOf(
            RgbColor.fromInt(0xCF7244),
            RgbColor.fromInt(0xCC9433)
        ),
        listOf(
            RgbColor.fromInt(0xCC9433),
            RgbColor.fromInt(0xA17232)
        ),
    ),
    PURPLE_VIOLET(
        10,
        listOf(
            RgbColor.fromInt(0x9662D4),
            RgbColor.fromInt(0xB966B6)
        ),
        listOf(
            RgbColor.fromInt(0x634691),
            RgbColor.fromInt(0x9250A2)
        ),
    ),
    LIGHT_GREEN_GREEN(
        11,
        listOf(
            RgbColor.fromInt(0x3D9755),
            RgbColor.fromInt(0x89A650)
        ),
        listOf(
            RgbColor.fromInt(0x296A43),
            RgbColor.fromInt(0x5F8F44)
        ),
    ),
    BLUE_CYAN(
        12,
        listOf(
            RgbColor.fromInt(0x3D95BA),
            RgbColor.fromInt(0x50AD98)
        ),
        listOf(
            RgbColor.fromInt(0x306C7C),
            RgbColor.fromInt(0x3E987E)
        ),
    ),
    BLUE_LIGHT_BLUE(
        13,
        listOf(
            RgbColor.fromInt(0x538BC2),
            RgbColor.fromInt(0x4DA8BD)
        ),
        listOf(
            RgbColor.fromInt(0x38618C),
            RgbColor.fromInt(0x458BA1)
        ),
    ),
    PINK_DARK_PINK(
        14,
        listOf(
            RgbColor.fromInt(0xB04F74),
            RgbColor.fromInt(0xD1666D)
        ),
        listOf(
            RgbColor.fromInt(0x884160),
            RgbColor.fromInt(0xA65259)
        ),
    ),
    GRAY_LIGHT_GRAY(
        15,
        listOf(
            RgbColor.fromInt(0x637482),
            RgbColor.fromInt(0x7B8A97)
        ),
        listOf(
            RgbColor.fromInt(0x53606E),
            RgbColor.fromInt(0x384654)
        ),
    ),
    ;

    companion object {
        val byId = entries.associateBy { it.id }
    }
}