import org.gradle.kotlin.dsl.support.kotlinCompilerOptions

/*
 * This file was generated by the Gradle 'init' task.
 */


plugins {
    kotlin("jvm")
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
    gradlePluginPortal()
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = "21"
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}

tasks.withType<Test> {
    useJUnitPlatform()
}


group = "ski.gagar.vertigram"
version = "1.0.0-alpha41-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
