
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.xxx")
}

dependencies {
    api(libs.bundles.vertx.core)
    api(libs.bundles.kotlin.std)
    api(libs.bundles.slf4j.api)

    testImplementation(libs.junit.api)
    testRuntimeOnly (libs.junit.engine)

    dokkaPlugin(libs.dokka.versioning.plugin)
}

description = "Vertigram Util"
