/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.vertigram-module")
}

dependencies {
    api(libs.bundles.jackson)
    api(libs.bundles.vertx.core)
    api(libs.bundles.vertx.web)
    api(libs.bundles.vertx.web.client)
    api(libs.bundles.commons.lang3)
    api(libs.bundles.reflections)
    api(libs.bundles.slf4j.api)

    api(project(":vertigram-telegram-client"))
    api(project(":vertigram-core"))
    api(project(":vertigram-annotations"))

    testImplementation(libs.junit.api)
    testRuntimeOnly (libs.junit.engine)

    dokkaPlugin(libs.dokka.versioning.plugin)
}

description = "Vertigram"
