import org.jetbrains.dokka.gradle.DokkaTaskPartial

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.vertigram-module")
}

dependencies {
    api(libs.bundles.kotlin.std)
    api(project(":vertigram-annotations"))
    api(libsInternal.bundles.kotlinpoet)
    api(libsInternal.ksp.api)
}

description = "Vertigram Code Generators"

tasks.withType<DokkaTaskPartial>().configureEach {
    onlyIf { false }
}